### ISSUE TITLE
Tangram is not defined

### ISSUE THREAD

**Issue by humanitiesNerd** [transitland/route-spotter#1]
It produces a blank page

The console reports an error claiming that "Tangram is not defined" in bundle.js

**Comment by doublestranded** [comment]
Hi @humanitiesNerd! Thank you for your interest and reporting, and I apologize for the delayed response. I'm looking into this and will report shortly. In the meantime, check out http://transitland.github.io/route-spotter/ for a demo.

**Comment by humanitiesNerd** [comment]
@doublestranded  thank you !

But it seems to me that the on line version suffers fro the same symptom !

Please let me know !

**Comment by doublestranded** [comment]
@humanitiesNerd: I may have uncovered the reason for the error you received (and I'm working on a possible fix). Can I ask which browser and version you are using?

**Comment by humanitiesNerd** [comment]
@doublestranded Firefox 45.0.1 on Fedora 23

**Comment by humanitiesNerd** [comment]
Because you made me think bout this, I tried with Chrome and it works

So was it Firefox ?

I apologize

**Comment by doublestranded** [comment]
Hi @humanitiesNerd, no need to apologize and thank you for pointing this out! I'm glad Chrome on Fedora works for you. The route-spotter project is relying on great third-party tools and plugins not necessarily made to render on all browsers and operating systems (and the route-spotter's own code has has not been tested cross-browser), hence the difficulty viewing. Maybe in the future we can provide that :)
