### ISSUE TITLE
TriMet FeedFetcherWorker

### ISSUE THREAD

**Issue by irees** [transitland/route-spotter#10]
http://developer.trimet.org/schedule/gtfs.zip

FeedFetcher fails with:

    NoMethodError: undefined method `match' for #<Array:0x007fb20dfa0b10>

**Comment by drewda** [comment]
Looks like the underlying issue is that TriMet's GTFS feed doesn't have a `calendar.txt` file. This should be addressed by @irees on https://github.com/transitland/transitland-datastore/issues/308

I'll add in some better error handling on the FeedFetcher side so these errors get logged.

**Comment by drewda** [comment]
Fixed by https://github.com/transitland/transitland-datastore/issues/308
