### ISSUE TITLE
only list operators for which stops/routes/schedule have been imported

### ISSUE THREAD

**Issue by drewda** [transitland/route-spotter#2]
@doublestranded could you only include operators on the list that have routes/stops/schedule data available? This should be possible by always including a `?import_level=2,3,4` query parameter on all requests to the `operators` endpoint.

**Comment by doublestranded** [comment]
@drewda level 2,3,4 import filters have been added. Thanks for pointing that out!

**Comment by drewda** [comment]
:+1:
