### ISSUE TITLE
Handling this feed from Victoria, Australia

### ISSUE THREAD

**Issue by rmglennon** [transitland/route-spotter#8]
This feed from Victoria, Australia has a few issues with it, including subfolders, a zip that uses pkzip format, and being behind a checkbox.

http://data.ptv.vic.gov.au/downloads/gtfs.zip

Home page for the operator's feed: https://www.data.vic.gov.au/data/dataset/ptv-timetable-and-geographic-information-2015-gtfs

This feed was suggested through support channels.

**Comment by drewda** [comment]
Oops, looks like I duplicated this. We'll track under #11
